### ISSUE TITLE
Running code

### ISSUE THREAD

**Issue by NanAlbert** [cdb342/Codes-for-IJCAI-2022-Paper-Zero-Shot-Logit-Adjustment#1]
Hello, this paper seems interesting. If you can provide the training settings and the corresponding running code? 
Thank you so much!

**Comment by cdb342** [comment]
Hello, I have modified part of the code and uploaded the running code.

**Comment by NanAlbert** [comment]
Excellent work! There seems to be an error in the commands. The commands for CUB lose "--class_embedding sent".
python ./WGAN+ZLAP.py --dataset CUB --attSize 1024 --nz 1024 --syn_num 10 --ratio 30 --class_embedding sent

**Comment by NanAlbert** [comment]
Also, the authors seem to use the sentence vectors as the auxiliary information, whose dimension is 1024. Did the author conduct experiments using attributes (312-dimensional vectors) on CUB dataset? Whether the method proposed in this paper can also lead to improvements?

**Comment by cdb342** [comment]
> Excellent work! There seems to be an error in the commands. The commands for CUB lose "--class_embedding sent". python ./WGAN+ZLAP.py --dataset CUB --attSize 1024 --nz 1024 --syn_num 10 --ratio 30 --class_embedding sent

Thank you for pointing it out!

**Comment by cdb342** [comment]
> Also, the authors seem to use the sentence vectors as the auxiliary information, whose dimension is 1024. Did the author conduct experiments using attributes (312-dimensional vectors) on CUB dataset? Whether the method proposed in this paper can also lead to improvements?

I test with 312-D attributes on CUB and get the result of unseen=54.2%, seen=55.8%, h=55.0% with ratio=45 and syn_num=10. It is better than the result of f-CLSWAGN (unseen=43.7%, seen=57.7%, h=49.7%). A better result may be achieved by tuning the hyper-parameters.

**Comment by NanAlbert** [comment]
Thank you so much! Fascinating work!
