### ISSUE TITLE
关于合成不可见类

### ISSUE THREAD

**Issue by HanAccount** [cdb342/Codes-for-IJCAI-2022-Paper-Zero-Shot-Logit-Adjustment#2]
你好！非常感谢这么好的贡献
请问在gene_syn_feature()函数里发现也生成了语义属性，这个作用是什么呢？
并且在分类时我看到你代码里写的train_att=torch.cat((train_att_,syn_att)),在分类阶段
并没有看到这个的使用。因为在分类代码里使用的attribute使用的还是self.att = data_loader.attribute

**Comment by cdb342** [comment]
你好，我已经上传了新版本代码，删除了冗余部分并添加了注释。
