### ISSUE TITLE
CE-GZSL-ZLAP

### ISSUE THREAD

**Issue by yangjingqi99** [cdb342/Codes-for-IJCAI-2022-Paper-Zero-Shot-Logit-Adjustment#5]
作者您好，请问可以提供一下CE-GZSL+ZLAP的代码吗

**Comment by cdb342** [comment]
只需要稍微修改源代码的分类损失就行了https://github.com/Hanzy1996/CE-GZSL

**Comment by yangjingqi99** [comment]
> 

好的，谢谢您！

**Comment by yangjingqi99** [comment]
> 只需要稍微修改源代码的分类损失就行了https://github.com/Hanzy1996/CE-GZSL

![image](https://user-images.githubusercontent.com/57439185/175798210-b8088f03-2428-442b-9833-90010bab83c4.png)
![image](https://user-images.githubusercontent.com/57439185/175798316-f06816f3-5bd7-4747-90c1-4c98f650bc12.png)

这里CE-GZSL得到的logits（embed）是2048维的，无法和先验概率相加，您是怎么处理的呢？还是说logits是经过model(LINEAR_LOGSOFTMAX)的output呢？

**Comment by yangjingqi99** [comment]
请问可以截图一下您在CE-GZSL中具体改动的部分吗，我自己改了后AWA2最高只能跑到70.4
![image](https://user-images.githubusercontent.com/57439185/175804304-cc1fd875-783a-46e8-b6a2-459d30c74b6c.png)

**Comment by yangjingqi99** [comment]
![image](https://user-images.githubusercontent.com/57439185/175804405-058b0045-a46b-46e6-a65f-be62432a0583.png)
我是这样改的

**Comment by cdb342** [comment]
> ![image](https://user-images.githubusercontent.com/57439185/175804405-058b0045-a46b-46e6-a65f-be62432a0583.png) 我是这样改的

还需把分类器改成prototype learner

**Comment by yangjingqi99** [comment]
> > ![image](https://user-images.githubusercontent.com/57439185/175804405-058b0045-a46b-46e6-a65f-be62432a0583.png) 我是这样改的
> 
> 还需把分类器改成prototype learner
很抱歉再次叨扰您，我按照您说的加入了prototype learner，但是只能复现到60，这是我修改的地方：
![image](https://user-images.githubusercontent.com/57439185/176339901-56c7e99c-7ba3-4cae-932a-881768fa6c1e.png)
我还尝试了这样：
![image](https://user-images.githubusercontent.com/57439185/176340172-0ae7b16f-ac78-4725-af0a-7577ec4e7887.png)
都没有达到预期结果，也逐句调试看了，但没有发现什么问题。。

**Comment by yangjingqi99** [comment]
image 我是这样改的

还需把分类器改成prototype learner
很抱歉再次叨扰您，我按照您说的加入了prototype learner，但是只能复现到60，这是我修改的地方：
![image](https://user-images.githubusercontent.com/57439185/176340911-28ad9bd7-fed0-4eb0-8f6d-c2784c285323.png)

我还尝试了这样：
![image](https://user-images.githubusercontent.com/57439185/176340980-2d9ff69e-df4b-4e3e-8a89-95b667229dec.png)
都没有达到预期结果，也逐句调试看了，但没有发现什么问题。。

**Comment by yangjingqi99** [comment]
我用的是3090，跑了1000轮

**Comment by cdb342** [comment]
> image 我是这样改的
> 
> 还需把分类器改成prototype learner 很抱歉再次叨扰您，我按照您说的加入了prototype learner，但是只能复现到60，这是我修改的地方： ![image](https://user-images.githubusercontent.com/57439185/176340911-28ad9bd7-fed0-4eb0-8f6d-c2784c285323.png)
> 
> 我还尝试了这样： ![image](https://user-images.githubusercontent.com/57439185/176340980-2d9ff69e-df4b-4e3e-8a89-95b667229dec.png) 都没有达到预期结果，也逐句调试看了，但没有发现什么问题。。

prototype有做归一化吗，有试过调整p0_Y的值吗

**Comment by yangjingqi99** [comment]
propo做了归一化，
![image](https://user-images.githubusercontent.com/57439185/176366447-1c338b8a-4eca-46cf-8875-9702326bf9f3.png)
ratio用的是您在论文中给出的AWA2数据集上最优值1000，请问您在CE-GZSL-ZLAP上设置的是多少呢？

**Comment by cdb342** [comment]
![2022-06-29 14-48-21 的屏幕截图](https://user-images.githubusercontent.com/61510717/176370281-d0762252-4d02-49c2-94c1-0de7acd3f55d.png)
在CE-GZSL上是28,也可以在这个值上下调整一下试试效果。

**Comment by yangjingqi99** [comment]
我设置了ratio=28,在运行的时候发现它的准确率变化比较奇怪，一开始比较高然后慢慢往下降，如图：
![image](https://user-images.githubusercontent.com/57439185/176372572-4278a76f-52ab-49e3-bbc4-6def0b7b47d5.png)
对比原CE-GZSL的结果（一直慢慢往上升）：
![image](https://user-images.githubusercontent.com/57439185/176372952-c8583803-022d-456b-bed7-1a7d3a2cbf1c.png)
请问您运行的时候准确率也是这样变化吗，最优轮是多少轮呢？

**Comment by cdb342** [comment]
CE-GZSL+ZLAP
![2022-06-29 15-48-17 的屏幕截图](https://user-images.githubusercontent.com/61510717/176381670-3152240c-89d7-4b64-9de7-7d2a8c71b626.png)
CE-GZSL
![2022-06-29 15-50-11 的屏幕截图](https://user-images.githubusercontent.com/61510717/176382003-792437b8-8b66-4506-9497-d4a15119e2ad.png)
这是我之前调参的时候跑的一组结果，基本上在30个epoch内能达到最优。CE-GZSL的参数包括生成样本数量我是按原论文设的，除了因为显存原因把batch size改成512（SUN上是256）。加入ZLAP只引入了ratio这个超参，建议再调一调看看结果，加油！

**Comment by yangjingqi99** [comment]
> 

非常您的耐心指导！我现在可以跑到71了，但是和您在论文中报告的还是差1个点。请问超参数这里还有什么需要改的吗，比如说这个tem值您在CE-GZSL-ZLAP中使用的是多少呢？（我用的是代码中默认的0.04）还有分类器训练轮数（我用的是CE默认的25，但是我看您默认的是60）
![image](https://user-images.githubusercontent.com/57439185/176582358-13420853-ac25-4650-8be5-9df69ce5d4b0.png)

**Comment by cdb342** [comment]
> > 
> 
> 非常您的耐心指导！我现在可以跑到71了，但是和您在论文中报告的还是差1个点。请问超参数这里还有什么需要改的吗，比如说这个tem值您在CE-GZSL-ZLAP中使用的是多少呢？（我用的是代码中默认的0.04）还有分类器训练轮数（我用的是CE默认的25，但是我看您默认的是60） ![image](https://user-images.githubusercontent.com/57439185/176582358-13420853-ac25-4650-8be5-9df69ce5d4b0.png)

tem是0.04，我直接参考了这个工作的设置https://github.com/universome/class-norm 。由于这一类方法输出的是分类器所有训练轮次下的最优结果，所以分类器训练轮数我取了一个较大的值，能够确保最优epoch包含在内，另外调整这个值还会影响随机数。

**Comment by yangjingqi99** [comment]
> > > 
> > 
> > 
> > 非常您的耐心指导！我现在可以跑到71了，但是和您在论文中报告的还是差1个点。请问超参数这里还有什么需要改的吗，比如说这个tem值您在CE-GZSL-ZLAP中使用的是多少呢？（我用的是代码中默认的0.04）还有分类器训练轮数（我用的是CE默认的25，但是我看您默认的是60） ![image](https://user-images.githubusercontent.com/57439185/176582358-13420853-ac25-4650-8be5-9df69ce5d4b0.png)
> 
> tem是0.04，我直接参考了这个工作的设置https://github.com/universome/class-norm 。由于这一类方法输出的是分类器所有训练轮次下的最优结果，所以分类器训练轮数我取了一个较大的值，能够确保最优epoch包含在内，另外调整这个值还会影响随机数。

大神，我从昨天到今天能调的参数都调了，最高就到71.05，跟您论文中报告的差一个点，请问您可以把具体再CE-GZSL上改动的地方和参数截图让我看一下吗（明天下午开组会复现不出来会被导师骂死55555。。。）

**Comment by cdb342** [comment]
![2022-06-30 23-56-15 的屏幕截图](https://user-images.githubusercontent.com/61510717/176723918-ece2906d-cad8-4fbb-add1-e996d8092884.png)
![2022-06-30 23-57-30 的屏幕截图](https://user-images.githubusercontent.com/61510717/176723875-cf873451-bca3-459d-a9b6-37e935a470ea.png)
![2022-06-30 23-56-47 的屏幕截图](https://user-images.githubusercontent.com/61510717/176723888-07cbb3b3-69bc-4742-9cd7-74ca92c2a6c2.png)
![2022-06-30 23-57-55 的屏幕截图](https://user-images.githubusercontent.com/61510717/176723840-0e50faeb-845b-483a-ab14-f90ae52504be.png)
![2022-06-30 23-57-46 的屏幕截图](https://user-images.githubusercontent.com/61510717/176723863-23eb649f-f1ed-4797-b032-5f97f01dd79f.png)
结果可能会受到不同的环境带来的随机性的影响。

**Comment by yangjingqi99** [comment]
非常感谢您深夜的耐心回复！在您的帮助下现在可以复现到71.24了，但是您少截了一张val_gzsl的图，
![image](https://user-images.githubusercontent.com/57439185/176801818-4a060e8e-6ee5-416d-a8f8-7e172f1e92fc.png)
烦请您截图看一下，我觉得应该就是这里的问题了。（我用的环境是3090+pytorch1.11.0,应该会优化的更好）

**Comment by cdb342** [comment]
![2022-07-01 12-34-39 的屏幕截图](https://user-images.githubusercontent.com/61510717/176825977-b170d8bf-273d-4836-b03d-8d9b024ab27a.png)
这里没用什么trick。我跑这组实验的环境是2080ti+python3.7+pytorch1.11.0+cu102

**Comment by HanAccount** [comment]
看到你们的讨论我想问一下 最终分类器只能用投影的方式吗？ 使用一个全连接层不行吗 这是为什么呢

**Comment by cdb342** [comment]
> 看到你们的讨论我想问一下 最终分类器只能用投影的方式吗？ 使用一个全连接层不行吗 这是为什么呢

全连接也是可以的，用prototype效果会更好一点。

**Comment by yangjingqi99** [comment]
> > 看到你们的讨论我想问一下 最终分类器只能用投影的方式吗？ 使用一个全连接层不行吗 这是为什么呢
> 
> 全连接也是可以的，用prototype效果会更好一点。
大神，我调了两天参，还是没有达到72，之前能跑到71.54是因为我使用了大batchsize:4096,如果使用您提供的batchsize:512最多只能跑到70，差了2个点。大batchsize收敛很慢，在125轮达到最优；
这是我使用的参数：--dataset AWA2 --class_embedding att --syn_num 2400 --batch_size 512 --attSize 85 --nz 85 --embedSize 2048 --outzSize 512 --nhF 2048 --ins_weight 0.001 --cls_weight 0.001 --ins_temp 10.0 --cls_temp 1.0 --manualSeed 9182 --nclass_all 50 --nclass_seen 40
![image](https://user-images.githubusercontent.com/57439185/177065674-0c825680-61a7-4c00-bb20-0150091c49f9.png)
![image](https://user-images.githubusercontent.com/57439185/177065721-a69827d4-7936-449a-9f70-bae25df0f076.png)
![image](https://user-images.githubusercontent.com/57439185/177065774-93628205-d922-4777-8bed-8e381fc6c6a9.png)

其他都是CE-GZSL默认的，请问和您使用的有区别吗？

**Comment by cdb342** [comment]
> > > 看到你们的讨论我想问一下 最终分类器只能用投影的方式吗？ 使用一个全连接层不行吗 这是为什么呢
> > 
> > 
> > 全连接也是可以的，用prototype效果会更好一点。
> > 大神，我调了两天参，还是没有达到72，之前能跑到71.54是因为我使用了大batchsize:4096,如果使用您提供的batchsize:512最多只能跑到70，差了2个点。大batchsize收敛很慢，在125轮达到最优；
> > 这是我使用的参数：--dataset AWA2 --class_embedding att --syn_num 2400 --batch_size 512 --attSize 85 --nz 85 --embedSize 2048 --outzSize 512 --nhF 2048 --ins_weight 0.001 --cls_weight 0.001 --ins_temp 10.0 --cls_temp 1.0 --manualSeed 9182 --nclass_all 50 --nclass_seen 40
> > ![image](https://user-images.githubusercontent.com/57439185/177065674-0c825680-61a7-4c00-bb20-0150091c49f9.png)
> > ![image](https://user-images.githubusercontent.com/57439185/177065721-a69827d4-7936-449a-9f70-bae25df0f076.png)
> > ![image](https://user-images.githubusercontent.com/57439185/177065774-93628205-d922-4777-8bed-8e381fc6c6a9.png)
> 
> 其他都是CE-GZSL默认的，请问和您使用的有区别吗？
我用了他github上的随机数种子
![2022-07-05 11-37-15 的屏幕截图](https://user-images.githubusercontent.com/61510717/177244728-be32fb80-86e3-4cdb-a9f8-85e4f0d71dea.png)

**Comment by yangjingqi99** [comment]
> 
我改了，跑到70.36，请问您--lr 和 --lr_decay_epoch 设置的是多少吖？

**Comment by yangjingqi99** [comment]
麻烦您截图一下完整的超参，我比照一下。

**Comment by cdb342** [comment]
> > 
> 
> 我改了，跑到70.36，请问您--lr 和 --lr_decay_epoch 设置的是多少吖？

0.0001和100,这些参数我都按照他的论文和project来的。要不测一下相同设置下加不加我们方法的性能差值，以及在不同python环境或者不同设备下原CE-GZSL方法batch size为512时的性能。
