### ISSUE TITLE
关于先验概率公式

### ISSUE THREAD

**Issue by yangjingqi99** [cdb342/Codes-for-IJCAI-2022-Paper-Zero-Shot-Logit-Adjustment#6]
![Eq10](https://user-images.githubusercontent.com/57439185/175763560-34d85bd9-1628-4106-b2a4-ba6ffdd1db2d.png)
请问这个公式具体是什么意思呢

**Comment by yangjingqi99** [comment]
![image](https://user-images.githubusercontent.com/57439185/175763601-ffce8ddb-1278-4eca-b117-b42269f15a70.png)
这里公式中是相乘，但是在代码中为什么是先将先验概率取对数后再相加呢

**Comment by cdb342** [comment]
> ![Eq10](https://user-images.githubusercontent.com/57439185/175763560-34d85bd9-1628-4106-b2a4-ba6ffdd1db2d.png) 请问这个公式具体是什么意思呢

这里是一步近似。如果概率p=[0.1,0.8,0.1]，取概率q=[0,1,0]能使sum(p*q)最大。公式Eq. 9里面算的是概率的倒数，和这个例子略有不同，但是思想上类似。

**Comment by cdb342** [comment]
> ![image](https://user-images.githubusercontent.com/57439185/175763601-ffce8ddb-1278-4eca-b117-b42269f15a70.png) 这里公式中是相乘，但是在代码中为什么是先将先验概率取对数后再相加呢

理论上是一样的，这样可以直接调用F.cross_entropy计算损失。

**Comment by yangjingqi99** [comment]
![image](https://user-images.githubusercontent.com/57439185/175771430-4de73b5d-f9a9-4be7-8173-8e695f8ca570.png)
![image](https://user-images.githubusercontent.com/57439185/175771445-53382abc-e24d-4804-8ccf-3f9ba52e738a.png)
![image](https://user-images.githubusercontent.com/57439185/175771452-00eead6e-0b74-4cbf-b88a-77ba0885428f.png)
AH和（1/AS+1/AH）成正比关系，为什么得到（1/AS+1/AH)的上限等于得到AH的下限呢

**Comment by yangjingqi99** [comment]
![image](https://user-images.githubusercontent.com/57439185/175771683-a499a4f1-729f-4f74-8a4b-e89af31df7b6.png)
请问这个公式里的
![image](https://user-images.githubusercontent.com/57439185/175771699-a909e10c-7dc4-473e-9773-ef37d8e7c097.png)这一项是怎么来的，具体是什么含义呢？

**Comment by cdb342** [comment]
> ![image](https://user-images.githubusercontent.com/57439185/175771683-a499a4f1-729f-4f74-8a4b-e89af31df7b6.png) 请问这个公式里的 ![image](https://user-images.githubusercontent.com/57439185/175771699-a909e10c-7dc4-473e-9773-ef37d8e7c097.png)这一项是怎么来的，具体是什么含义呢？
![微信图片_20220625211743](https://user-images.githubusercontent.com/61510717/175775186-380ff6c7-7d60-4855-accd-a701039254d5.jpg)

我们把它作为可见类与不可见类间先验。

**Comment by cdb342** [comment]
> ![image](https://user-images.githubusercontent.com/57439185/175771430-4de73b5d-f9a9-4be7-8173-8e695f8ca570.png) ![image](https://user-images.githubusercontent.com/57439185/175771445-53382abc-e24d-4804-8ccf-3f9ba52e738a.png) ![image](https://user-images.githubusercontent.com/57439185/175771452-00eead6e-0b74-4cbf-b88a-77ba0885428f.png) AH和（1/AS+1/AH）成正比关系，为什么得到（1/AS+1/AH)的上限等于得到AH的下限呢

这里是反比

**Comment by yangjingqi99** [comment]
> > ![image](https://user-images.githubusercontent.com/57439185/175771430-4de73b5d-f9a9-4be7-8173-8e695f8ca570.png) ![image](https://user-images.githubusercontent.com/57439185/175771445-53382abc-e24d-4804-8ccf-3f9ba52e738a.png) ![image](https://user-images.githubusercontent.com/57439185/175771452-00eead6e-0b74-4cbf-b88a-77ba0885428f.png) AH和（1/AS+1/AH）成正比关系，为什么得到（1/AS+1/AH)的上限等于得到AH的下限呢
> 
> 这里是反比

嗯嗯是的，是我看错了

**Comment by yangjingqi99** [comment]
> > ![image](https://user-images.githubusercontent.com/57439185/175771683-a499a4f1-729f-4f74-8a4b-e89af31df7b6.png) 请问这个公式里的 ![image](https://user-images.githubusercontent.com/57439185/175771699-a909e10c-7dc4-473e-9773-ef37d8e7c097.png)这一项是怎么来的，具体是什么含义呢？
> > ![微信图片_20220625211743](https://user-images.githubusercontent.com/61510717/175775186-380ff6c7-7d60-4855-accd-a701039254d5.jpg)
> 
> 我们把它作为可见类与不可见类间先验。

明白了，非常感谢您的耐心回复，期待您的下一篇论文！
