### ISSUE TITLE
分类器C(x)

### ISSUE THREAD

**Issue by whisper2234** [cdb342/Codes-for-IJCAI-2022-Paper-Zero-Shot-Logit-Adjustment#8]
您好，我想问一下您在分类器Cx那里
![image](https://user-images.githubusercontent.com/64779251/190091531-1e82fd9b-cf53-46e3-be4d-6cfc2bdf4b4e.png)
为什么没有像公式里那样先算余弦相似度了
![image](https://user-images.githubusercontent.com/64779251/190091835-5e72f606-9e18-447b-a053-9b5c587f998b.png)

**Comment by cdb342** [comment]
> 您好，我想问一下您在分类器Cx那里 ![image](https://user-images.githubusercontent.com/64779251/190091531-1e82fd9b-cf53-46e3-be4d-6cfc2bdf4b4e.png) 为什么没有像公式里那样先算余弦相似度了 ![image](https://user-images.githubusercontent.com/64779251/190091835-5e72f606-9e18-447b-a053-9b5c587f998b.png)

归一化后的点积就是余弦相似度
